# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_client.models.whole_organism import WholeOrganism

class TestWholeOrganism(unittest.TestCase):
    """WholeOrganism unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WholeOrganism:
        """Test WholeOrganism
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WholeOrganism`
        """
        model = WholeOrganism()
        if include_optional:
            return WholeOrganism(
            )
        else:
            return WholeOrganism(
        )
        """

    def testWholeOrganism(self):
        """Test WholeOrganism"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
