# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_client.models.gene_location1 import GeneLocation1

class TestGeneLocation1(unittest.TestCase):
    """GeneLocation1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeneLocation1:
        """Test GeneLocation1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeneLocation1`
        """
        model = GeneLocation1()
        if include_optional:
            return GeneLocation1(
                assembly = 'GRCh38',
                chromosome = 'chrC',
                start = 0,
                end = 0
            )
        else:
            return GeneLocation1(
                assembly = 'GRCh38',
                chromosome = 'chrC',
                start = 0,
                end = 0,
        )
        """

    def testGeneLocation1(self):
        """Test GeneLocation1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
