# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_client.models.page_layout import PageLayout

class TestPageLayout(unittest.TestCase):
    """PageLayout unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageLayout:
        """Test PageLayout
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageLayout`
        """
        model = PageLayout()
        if include_optional:
            return PageLayout(
                blocks = [
                    igvf_client.models.page_layout_components.Page Layout Components(
                        @id = '', 
                        @type = '', 
                        body = '', 
                        direction = '', )
                    ]
            )
        else:
            return PageLayout(
        )
        """

    def testPageLayout(self):
        """Test PageLayout"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
