# coding: utf-8

"""
    IGVF Project API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_client.models.item_type import ItemType

class TestItemType(unittest.TestCase):
    """ItemType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemType(self):
        """Test ItemType"""
        # inst = ItemType()

if __name__ == '__main__':
    unittest.main()
