name: publish-to-pypi
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.9.0
      environment:
        name: pypi
        url: https://pypi.org/p/<your-pypi-project-name>
      permissions:
        id-token: write
