name: Publish to pypi
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/igvf-client/
    permissions:
      id-token: write
      actions: read
      contents: read
      pages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip
        pip install build twine==6.0.1
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.9.0
